"""Evidence-bound explanation guard + generation (RIS-19, `RW-AI-011`)."""

from .generation import (
    DEFAULT_EXPLANATION_MODEL,
    EXPLANATION_PROMPT_VERSION,
    Audience,
    EdgeEvidence,
    ExplanationTransport,
    GeneratedExplanation,
    NodeExplanationContext,
    PathSummary,
    StructuredNumber,
    build_node_context,
    citation_markers_in,
    generate_node_explanation,
    strip_citation_markers,
)
from .guard import (
    ExplanationPayload,
    GuardResult,
    extract_numeric_tokens,
    guard_explanation,
)
from .payload import payload_for_node, payload_for_run
from .qa import (
    DEFAULT_MAX_TOOL_CALLS,
    QA_PROMPT_VERSION,
    QaAnswer,
    QaToolTransport,
    ToolCallAudit,
    answer_question,
)
from .tools import (
    TOOL_NAMES,
    ClosedToolRegistry,
    RunToolContext,
    SecurityTerms,
    ToolArgumentError,
    ToolResult,
    ToolSpec,
    UnknownToolError,
    build_registry,
)

__all__ = [
    "DEFAULT_EXPLANATION_MODEL",
    "DEFAULT_MAX_TOOL_CALLS",
    "EXPLANATION_PROMPT_VERSION",
    "QA_PROMPT_VERSION",
    "TOOL_NAMES",
    "Audience",
    "ClosedToolRegistry",
    "EdgeEvidence",
    "ExplanationPayload",
    "ExplanationTransport",
    "GeneratedExplanation",
    "GuardResult",
    "NodeExplanationContext",
    "PathSummary",
    "QaAnswer",
    "QaToolTransport",
    "RunToolContext",
    "SecurityTerms",
    "StructuredNumber",
    "ToolArgumentError",
    "ToolCallAudit",
    "ToolResult",
    "ToolSpec",
    "UnknownToolError",
    "answer_question",
    "build_node_context",
    "build_registry",
    "citation_markers_in",
    "extract_numeric_tokens",
    "generate_node_explanation",
    "guard_explanation",
    "payload_for_node",
    "payload_for_run",
    "strip_citation_markers",
]
